server {
    server_name zenmoovz.com www.zenmoovz.com;

    location / {
        proxy_pass http://127.0.0.1:3001;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/zenmoovz.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/zenmoovz.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

server {
    server_name kiosk.zenmoovz.com;

    location / {
        proxy_pass http://127.0.0.1:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/zenmoovz.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/zenmoovz.com/privkey.pem; # managed by Certbot
###################KIOSK-Certification Authorities##########################################
    #ssl_client_certificate /etc/nginx/ssl/kiosk-ca.crt;
    #ssl_verify_client on;
    #add_header X-SSL-Client-Verify $ssl_client_verify always;
    #add_header X-SSL-Client-DN $ssl_client_s_dn always;
############################################################################################
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    server_name api.zenmoovz.com;

    location / {
        proxy_pass http://127.0.0.1:9001;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/zenmoovz.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/zenmoovz.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = www.zenmoovz.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = zenmoovz.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name zenmoovz.com www.zenmoovz.com;
    return 404; # managed by Certbot




}

server {
    if ($host = api.zenmoovz.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name api.zenmoovz.com;
    return 404; # managed by Certbot


}

server {
    if ($host = kiosk.zenmoovz.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name kiosk.zenmoovz.com;
    return 404; # managed by Certbot


}
