###Docker
FROM maven  AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean install

# Stage 3: Create the runtime image
FROM azul/zulu-openjdk:21-latest
WORKDIR /
COPY --from=build /app/target/Renew-0.0.1-SNAPSHOT.jar /Renew-0.0.1-SNAPSHOT.jar
EXPOSE 9000
CMD ["java", "-jar", "Renew-0.0.1-SNAPSHOT.jar"]



## Application.yml
server:
  port: 8079


spring:
  data:
    mongodb:
      uri: mongodb+srv://username:password@url&connectTimeoutMS=30000&socketTimeoutMS=30000
      database: dbname


  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
	  
	  
###Docker Compose 	  
version: "3.1"

services:

  innoura_website_api:
        image: imagename
        container_name: containername
        restart: always
        ports:
           - 8079:8079
