server:
  port: 9001
  spring:
    servlet:
      multipart:
        enabled: true



spring:
  data:
    mongodb:
      uri: mongodb+srv://healthmedpro:mawUDKsQR4TATgpQ@cluster0.3yian.mongodb.net/med-elite?retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=30000
      database: med-elite


  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: w+vmNlr8JP7z83MCMrz5JUccURfid2bORo5JD5E5TQpY1VRyx+YykKcnNEF1+wXZ